# Generated by Django 4.1.5 on 2023-01-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
